name: ING Corda Fork Minimal Build

on:
  push:
    branches:
      - ing-fork

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        env:
          ING_MINIMAL_BUILD: 1

      - name: Publish to GitHub Packages
        run: ./gradlew publish --continue
        env:
          ING_MINIMAL_BUILD: 1
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
