name: ING Corda Fork Minimal Build

env:
  ING_MINIMAL_BUILD: 1
  GITHUB_USERNAME: ${{ secrets.GH_PACKAGES_USER }}
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

on:
  push:
    branches:
      - ing-fork

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew assemble --stacktrace --build-cache --parallel

  publish:
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8.0.x (FX)
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.x
          java-package: jdk+fx

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to GitHub Packages (should never fail)
        run: ./gradlew publish --continue --build-cache --parallel
        env:
          ING_MINIMAL_BUILD: 1
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
